apiVersion: v1
kind: Service
metadata:
  name: evm-decompiler-rest-serv
spec:
  # specify target deployment for incoming requests
  selector:
    app: evm-decompiler-rest-depl
  ports:
    - protocol: TCP
      port: 7639
  # NodePort open this service for requests on each node in the cluster
  # type: NodePort

  # Google Cloud load balancer
  type: LoadBalancer
